server:
  port:8080

spring:
  profiles:
    include: secrets
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret-key: ${jwt.secret-key}
    access:
      expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    refresh:
      expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${mail.username} # SMTP 서버 로그인 아이디
    password: ${mail.password} # SMTP 서버 로그인 앱 패스워드
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)
cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}
